<#
    .Synopsis
        This script will convert a WDAC policy XML file (generated by the WDAC Wizard for example) and convert it to the binary format required for deployment.
    
    .DESCRIPTION
        PowerShell script that can be used to convert a WDAC Policy from the XML to binary format. For example this script can be used
        to convert a manually modified WDAC XML policy file into the .cip format that can then be used to deploy to a Windows 10/11 device.
        
    .EXAMPLE
        1. Convert a WDAC policy XML file to binary.  The binary file is created based on the policy GUID.
           .\ConvertPolicyXmlToBinary.ps1 -XmlPolicyFile MyAuditPolicy.xml
 
        2. Convert a WDAC policy XML file to binary file using the file name specified.
           .\ConvertPolicyXmlToBinary.ps1 -XmlPolicyFile MyAuditPolicy.xml -BinaryFile MyAuditPolicy.cip
	   
    .NOTES
	        Author:  Andrew Silcock
	        Version: 1.0
          Created: 28-Mar-2023
          Updated: 28-Mar-2023
    
     .LINK
        https://github.com/andrewitdevlab/blog-content/Windows Defender/Scripts/WDAC/Convert Policy/ConvertPolicyXmlToBinary.ps1
#>


<#
 # This script will convert a WDAC policy XML file (generated by the WDAC Wizard for example) and convert it to the binary format required for deployment.
 #
 # Pre-requisites:
 #  - A windows device where PowerSHell scripts can be executed (the required PS cmdlets are built into Windows) 
 #
 # Example usage:
 #   1. Convert a WDAC policy XML file to binary.  The binary file is created based on the policy GUID.
 #       .\ConvertPolicyXmlToBinary.ps1 -XmlPolicyFile MyAuditPolicy.xml
 #
 #   2. Convert a WDAC policy XML file to binary file using the file name specified.
 #       .\ConvertPolicyXmlToBinary.ps1 -XmlPolicyFile MyAuditPolicy.xml -BinaryFile MyAuditPolicy.cip
 #>
param
(
    [parameter(Mandatory=$true)]
    [string] $XmlPolicyFile,
    [parameter(Mandatory=$false)]
    [string] $BinaryFile

)

# If a Binary file name hasn't been provided generate the binary file name from the Policy GUID
if (-not $BinaryFile)
{
    [xml] $XmlPolicy = Get-Content $XmlPolicyFile
    $BinaryFile = "{0}.cip" -f $XmlPolicy.SiPolicy.PolicyID
}

ConvertFrom-CIPolicy -XmlFilePath $XmlPolicyFile -BinaryFilePath $BinaryFile 
